name: vm_fm_4
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+0.0.1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # local database
  shared_preferences: ^2.2.0
  shared_preferences_foundation: ^2.2.2

  # dependency injection
  get_it: ^7.6.0
  injectable: ^2.1.2

  # provider --state management
  provider: ^6.0.5

  # network --service management
  dio: ^5.2.1+1
  dartz: ^0.10.1

  # route management
  auto_route: ^7.7.0

  # json management
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5

  # log management
  logger: ^1.4.0

  # persistent tab bar --for bottom navigation bar
  bottom_navy_bar: ^6.0.0

  # animated widgets
  animated_widgets: ^1.1.0

  # localizations
  easy_localization: ^3.0.2
  timezone: ^0.9.0

  # firebase --for push notification
  firebase_core: ^2.11.0
  firebase_messaging: ^14.5.0
  firebase_analytics: ^10.3.0
  flutter_local_notifications: ^14.1.1
  rxdart: ^0.27.7

  # device info --get device info
  device_info_plus: ^9.0.2

  # snackbar
  top_snackbar_flutter: ^3.1.0

  # loading button
  rounded_loading_button: ^2.1.0

  # badgrs and url launcher
  badges: ^3.1.1
  url_launcher: ^6.1.12

  # image picker, file picker
  image_picker: ^1.0.1
  file_picker: ^5.3.3
  path_provider: ^2.0.15

  # for image cropper
  http_parser: ^4.0.2

  # accordion --ui
  accordion: ^2.5.1

  # icons
  cupertino_icons: ^1.0.2

  # internet connection checker
  internet_connection_checker: ^1.0.0+1

  # form builder
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0

  # animated text
  animated_text_kit: ^4.2.2

  # barcode scanner
  flutter_barcode_scanner: ^2.0.0
  dropdown_search: ^5.0.6

  # number picker
  numberpicker: ^2.1.2

  # file downloader
  flutter_file_downloader: ^1.1.2
  simple_downloader: ^0.0.3+1
  flutter_download_manager: ^0.5.5
  internet_file: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # for auto router
  auto_route_generator: ^7.2.0

  # for auto router, code generation
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
